# Generated by Django 6.0.3 on 2026-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="studentPaymentCode",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
