# Generated by Django 6.0.3 on 2026-05-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_alter_mark_term"),
        ("core", "0002_auditlog_role_customuser"),
        ("students", "0002_student_studentpaymentcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stream",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="student",
            name="stream",
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                db_index=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("school", "name")},
        ),
        migrations.CreateModel(
            name="ClassStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capacity", models.PositiveIntegerField(default=40)),
                ("room_number", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_streams_taught",
                        to="academic.teacher",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_streams",
                        to="students.classroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_streams",
                        to="students.stream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Stream",
                "verbose_name_plural": "Class Streams",
                "ordering": ["classroom__level", "stream__name"],
                "unique_together": {("school", "classroom", "stream")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="class_stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.classstream",
            ),
        ),
    ]
