# Generated by Django 5.2.5 on 2026-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a passport-sized photo of the student', null=True, upload_to='students/photos/'),
        ),
    ]
