# Generated by Django 5.2.5 on 2026-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='mac', max_length=200, verbose_name='Parent/Guardian Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(default='0776203790', max_length=20, verbose_name='Guardian Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Legal Guardian'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], default='FATHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a passport-sized photo', null=True, upload_to='students/photos/'),
        ),
    ]
