# Generated by Django 5.2.5 on 2026-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='Official school badge/logo', null=True, upload_to='school/logos/'),
        ),
    ]
