# Generated by Django 5.2.5 on 2026-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_address_school_email_school_motto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
