# Generated by Django 6.0.3 on 2026-03-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feelineitem',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='other_requirements_total',
        ),
        migrations.AddField(
            model_name='feelineitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='finance.invoice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='finance.feestructure')),
            ],
        ),
    ]
