# Generated by Django 5.2.5 on 2026-03-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='category',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
