# Generated by Django 6.0.3 on 2026-04-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0002_remove_feelineitem_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_per_sms', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_config', to='core.school')),
            ],
        ),
    ]
