# Generated by Django 5.2.5 on 2026-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_feestructure_category_alter_feestructure_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='depositor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Deposit'), ('Mobile Money', 'Mobile Money')], default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
