# Generated by Django 6.0.3 on 2026-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_smstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
