# Generated by Django 5.2.5 on 2026-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
