# Generated by Django 6.0.3 on 2026-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_feeitem_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], db_index=True, max_length=1),
        ),
    ]
