# Generated by Django 6.0.3 on 2026-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_feestructure_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=100),
        ),
    ]
