# Generated by Django 6.0.3 on 2026-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank Transfer"),
                    ("MTN MobileMoney", "MTN Mobile Money"),
                    ("AirtelMoney", "Airtel Money"),
                    ("SchoolPay", "SchoolPay"),
                ],
                max_length=100,
            ),
        ),
    ]
