# Generated by Django 6.0.3 on 2026-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog_role_customuser"),
        ("finance", "0011_alter_payment_payment_method"),
        ("students", "0003_alter_stream_options_remove_student_classroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("school", "invoice_number"), name="unique_school_invoice_number"
            ),
        ),
    ]
