# Generated by Django 6.0.3 on 2026-03-31 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('items', models.TextField(help_text='List items separated by commas or new lines')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
    ]
