# Generated by Django 5.2.5 on 2026-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0004_student_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subject',
            name='classrooms',
            field=models.ManyToManyField(related_name='subjects', to='students.classroom'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='end_term_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mid_term_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='term',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RemoveField(
            model_name='mark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='opening_mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teacher_comment',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='updated_at',
        ),
    ]
