# Generated by Django 6.0.3 on 2026-04-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_mark_student_alter_mark_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='term',
            field=models.CharField(choices=[('Term One', 'Term One'), ('Term Two', 'Term Two'), ('Term Three', 'Term Three')], max_length=20),
        ),
    ]
