# Generated by Django 6.0.3 on 2026-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_mark_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20),
        ),
    ]
